# Generated by Django 4.0.3 on 2023-05-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
